on:
  workflow_dispatch:
    inputs:
      instance:
        default: d1
        required: True
        type: choice
        description: Select the instance
        options:
        - d1
        - s1
        - p1
        - test

      data_5K:
        type: boolean
        description: data_5K
      data_10K:
        type: boolean
        description: data_10K
      data_15K:
        type: boolean
        description: data_15K
      data_20K:
        type: boolean
        description: data_20K
      data_30K:
        type: boolean
        description: data_30K
      data_100K:
        type: boolean
        description: data_100K
      data_500K:
        type: boolean
        description: data_500K
      data_750K:
        type: boolean
        description: data_750K




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ inputs.instance }},
          echo ${{ inputs.data }},
          echo ${{ inputs.data_5K }},

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: (${{ github.event.inputs.data_5K == 'true' }} || ${{ github.event.inputs.data_10K == 'true' }})
        run: |
          echo "data_5K"  ${{ github.event.inputs.data_5K }}
          echo "data_10K" ${{ github.event.inputs.data_10K }}
          echo "data_15K"
          echo "data_20K"
          echo "data_30K"
          echo "data_100K"
          echo "data_500K"
          echo "data_750K"
          
          
          
        
      



        



    
