on:
  workflow_dispatch:
    inputs:
      name:
        type: multi-choice
        description: select packages
        options:
        - go-service1
        - go-service2
        - py-service1


      



        



    