on:
  workflow_dispatch:
    inputs:
      instance:
        default: d1
        required: True
        type: choice
        description: Select the instance
        options:
        - d1
        - s1
        - p1
        - test

      data:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Data'
        # Default value if no value is explicitly provided
        default: 'select the folder to upload the data'
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - data_5K
          - data_10K
          - data_15K
          - data_20K
          - data_30K
          - data_500K
          - data_750K

      data_5k:
        type: boolean
        description: data_5k or not


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ inputs.instance }},
          echo ${{ inputs.data }},
          echo ${{ inputs.boolean }},
      



        



    
